### ISSUE TITLE
Windows paths: hard coded or using Windows-specific functions?

### ISSUE THREAD

**Issue by markjam33** [jturner65/StraffordSOMVis#1]
When trying to load a pre-built map, the application is throwing an error. The context of the error indicates that it is trying to reference a Windows-style path in the Eclipse project directory. How can this be fixed?

Here is the error (plus context) from the Eclipse console:
5/7/19 1:02 PM | 00:00:15.050 | SOMProjConfigData::loadProjConfigForSOMExe:Start loading project config data for SOM Execution : /Users/markmyers/Documents/Development/GITLocal/data/projects/StraffordSOMVis/StraffordProject/SOM/StraffSOM_2019_04_26_08_00/SOM_EXEC_Proj_Config.txt
5/7/19 1:02 PM | 00:00:15.050 | fileIOManager:SOMProjConfigData::_loadFileIntoStringAra:SOMProjConfigData project config data for SOM Execution File loaded	Length : 21
5/7/19 1:02 PM | 00:00:15.051 | SOMProjConfigData::loadProjConfigForSOMExe:Finished loading project config data for SOM Execution
5/7/19 1:02 PM | 00:00:15.051 | SOMProjConfigData::loadSOMMap_Config:Start loading SOM Exe config data from D:\Eclipse Workspace\eclipse workspace\SOM_StraffordExp\StraffordProject\SOM\StraffSOM_2019_04_26_08_00\SOM_MapConfig_straff_Smp_112405_Dt_04_26_08_00.txt
java.io.FileNotFoundException: D:\Eclipse Workspace\eclipse workspace\SOM_StraffordExp\StraffordProject\SOM\StraffSOM_2019_04_26_08_00\SOM_MapConfig_straff_Smp_112405_Dt_04_26_08_00.txt (No such file or directory)
5/7/19 1:02 PM | 00:00:15.052 | fileIOManager:SOMProjConfigData::_loadFileIntoStringAra:!!SOM_MapDat Config File Failed to load
5/7/19 1:02 PM | 00:00:15.052 | SOM_MapDat::buildFromStringArray:Array of description information not correct format to build SOM_MapDat object.  Aborting.
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at base_Utils_Objects.FileIOManager._loadFileIntoStringAra(FileIOManager.java:55)
	at base_Utils_Objects.FileIOManager.loadFileIntoStringAra(FileIOManager.java:46)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:299)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:294)
	at base_SOM_Objects.som_utils.SOMProjConfigData.setSOM_UsePreBuilt(SOMProjConfigData.java:451)
	at base_SOM_Objects.SOMMapManager.loadPretrainedExistingMap(SOMMapManager.java:289)
	at strafford_SOM_PKG.Straff_SOMMapUIWin.launchMenuBtnHndlr(Straff_SOMMapUIWin.java:542)
	at base_UI_Objects.myDispWindow.checkCustMenuUIObjs(myDispWindow.java:1284)
	at base_UI_Objects.my_procApplet.drawWindowGuiObjs(my_procApplet.java:541)
	at base_UI_Objects.BaseBarMenu.drawMe(BaseBarMenu.java:336)
	at base_UI_Objects.myDispWindow.draw2D(myDispWindow.java:879)
	at base_UI_Objects.my_procApplet.drawUI(my_procApplet.java:451)
	at base_UI_Objects.my_procApplet._drawPriv(my_procApplet.java:430)
	at strafford_SOM_PKG.SOM_Strafford_UI_Main.draw(SOM_Strafford_UI_Main.java:113)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.lang.NullPointerException
	at base_SOM_Objects.som_ui.SOMMapUIWin.setUIValues(SOMMapUIWin.java:502)
	at base_SOM_Objects.SOMMapManager.setUIValsFromLoad(SOMMapManager.java:1178)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:301)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:294)
	at base_SOM_Objects.som_utils.SOMProjConfigData.setSOM_UsePreBuilt(SOMProjConfigData.java:451)
	at base_SOM_Objects.SOMMapManager.loadPretrainedExistingMap(SOMMapManager.java:289)
	at strafford_SOM_PKG.Straff_SOMMapUIWin.launchMenuBtnHndlr(Straff_SOMMapUIWin.java:542)
	at base_UI_Objects.myDispWindow.checkCustMenuUIObjs(myDispWindow.java:1284)
	at base_UI_Objects.my_procApplet.drawWindowGuiObjs(my_procApplet.java:541)
	at base_UI_Objects.BaseBarMenu.drawMe(BaseBarMenu.java:336)
	at base_UI_Objects.myDispWindow.draw2D(myDispWindow.java:879)
	at base_UI_Objects.my_procApplet.drawUI(my_procApplet.java:451)
	at base_UI_Objects.my_procApplet._drawPriv(my_procApplet.java:430)
	at strafford_SOM_PKG.SOM_Strafford_UI_Main.draw(SOM_Strafford_UI_Main.java:113)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by markjam33** [comment]
Look specifically at these lines:
5/7/19 1:02 PM | 00:00:15.051 | SOMProjConfigData::loadSOMMap_Config:Start loading SOM Exe config data from D:\Eclipse Workspace\eclipse workspace\SOM_StraffordExp\StraffordProject\SOM\StraffSOM_2019_04_26_08_00\SOM_MapConfig_straff_Smp_112405_Dt_04_26_08_00.txt
java.io.FileNotFoundException: D:\Eclipse Workspace\eclipse workspace\SOM_StraffordExp\StraffordProject\SOM\StraffSOM_2019_04_26_08_00\SOM_MapConfig_straff_Smp_112405_Dt_04_26_08_00.txt (No such file or directory)

Both reference a Windows-style path: "D:\Eclipse Workspace\..."

**Comment by markjam33** [comment]
Note that the above error also results in the application blocking, requiring a quit and restart.

**Comment by jturner65** [comment]
that's weird.  i don't hard code anything. was this launched from UI?

**Comment by markjam33** [comment]
Yes.

**Comment by markjam33** [comment]
It may be a setting in Eclipse for all I know, but I'm not sure where to look for this.

**Comment by jturner65** [comment]
was this a completely new pull?  A lot of things have changed.  There are hardcoded paths in the file data describing the pre-built maps that I have made, but that shouldn't matter- the path is ignored and rebuilt for those files.  This hasn't changed in a long time, either, so it should have come up before this.

**Comment by jturner65** [comment]
can you give me the entire console output?  so all the way back to the line that says "# threads : ..."

**Comment by markjam33** [comment]
I found the issue here. The paths in question are coming from the SOM_MapConfig_default.txt file in the config directory. So, this is not a bug, per se, but just a configuration that I need to change when running the application in my environment.

**Comment by jturner65** [comment]
I am fixing this anyway so that full paths are not saved in any configs.  they will be relative to the base path.
