### ISSUE TITLE
Incorrect path delimiter (Windows-specific) throwing error when loading Pre-built map

### ISSUE THREAD

**Issue by markjam33** [jturner65/StraffordSOMVis#6]
After whatever correction you made to fix the hard-coded pathing from the config files (now-closed Issue #1 ), the application is now throwing a similar error, but due instead to a single incorrect path delimiter. Here is the relevant part of the log:

5/8/19 5:23 PM | 00:00:16.273 | SOMProjConfigData::loadSOMMap_Config:Start loading SOM Exe config data from /Users/markmyers/Documents/Development/GITLocal/data/projects/StraffordSOMVis/StraffordProject/SOM/StraffSOM_2019_05_08_12_00\SOM_MapConfig_straff_Smp_112405_Dt_05_08_12_00.txt
java.io.FileNotFoundException: /Users/markmyers/Documents/Development/GITLocal/data/projects/StraffordSOMVis/StraffordProject/SOM/StraffSOM_2019_05_08_12_00\SOM_MapConfig_straff_Smp_112405_Dt_05_08_12_00.txt (No such file or directory)
5/8/19 5:23 PM | 00:00:16.275 | fileIOManager:SOMProjConfigData::_loadFileIntoStringAra:!!SOM_MapDat Config File Failed to load
5/8/19 5:23 PM | 00:00:16.275 | SOM_MapDat::buildFromStringArray:Array of description information not correct format to build SOM_MapDat object.  Aborting.
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at base_Utils_Objects.FileIOManager._loadFileIntoStringAra(FileIOManager.java:55)
	at base_Utils_Objects.FileIOManager.loadFileIntoStringAra(FileIOManager.java:46)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:305)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:300)
	at base_SOM_Objects.som_utils.SOMProjConfigData.setSOM_UsePreBuilt(SOMProjConfigData.java:529)
	at base_SOM_Objects.SOMMapManager.loadPretrainedExistingMap(SOMMapManager.java:300)
	at strafford_SOM_PKG.Straff_SOMMapUIWin.launchMenuBtnHndlr(Straff_SOMMapUIWin.java:542)
	at base_UI_Objects.myDispWindow.checkCustMenuUIObjs(myDispWindow.java:1284)
	at base_UI_Objects.my_procApplet.drawWindowGuiObjs(my_procApplet.java:541)
	at base_UI_Objects.BaseBarMenu.drawMe(BaseBarMenu.java:336)
	at base_UI_Objects.myDispWindow.draw2D(myDispWindow.java:879)
	at base_UI_Objects.my_procApplet.drawUI(my_procApplet.java:451)
	at base_UI_Objects.my_procApplet._drawPriv(my_procApplet.java:430)
	at strafford_SOM_PKG.SOM_Strafford_UI_Main.draw(SOM_Strafford_UI_Main.java:113)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.lang.NullPointerException
	at base_SOM_Objects.som_ui.SOMMapUIWin.setUIValues(SOMMapUIWin.java:551)
	at base_SOM_Objects.SOMMapManager.setUIValsFromLoad(SOMMapManager.java:1241)
	at base_SOM_Objects.som_utils.SOMProjConfigData.setUIValsFromLoad(SOMProjConfigData.java:313)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:309)
	at base_SOM_Objects.som_utils.SOMProjConfigData.loadSOMMap_Config(SOMProjConfigData.java:300)
	at base_SOM_Objects.som_utils.SOMProjConfigData.setSOM_UsePreBuilt(SOMProjConfigData.java:529)
	at base_SOM_Objects.SOMMapManager.loadPretrainedExistingMap(SOMMapManager.java:300)
	at strafford_SOM_PKG.Straff_SOMMapUIWin.launchMenuBtnHndlr(Straff_SOMMapUIWin.java:542)
	at base_UI_Objects.myDispWindow.checkCustMenuUIObjs(myDispWindow.java:1284)
	at base_UI_Objects.my_procApplet.drawWindowGuiObjs(my_procApplet.java:541)
	at base_UI_Objects.BaseBarMenu.drawMe(BaseBarMenu.java:336)
	at base_UI_Objects.myDispWindow.draw2D(myDispWindow.java:879)
	at base_UI_Objects.my_procApplet.drawUI(my_procApplet.java:451)
	at base_UI_Objects.my_procApplet._drawPriv(my_procApplet.java:430)
	at strafford_SOM_PKG.SOM_Strafford_UI_Main.draw(SOM_Strafford_UI_Main.java:113)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

In the first line of this log segment, there is the following path:
/Users/markmyers/Documents/Development/GITLocal/data/projects/StraffordSOMVis/StraffordProject/SOM/StraffSOM_2019_05_08_12_00\SOM_MapConfig_straff_Smp_112405_Dt_05_08_12_00.txt

On a POSIX machine, path delimiters are forward slashes, but here there is a backslash between the directory ("StraffSOM_2019_05_08_12_00") and the txt file ("SOM_MapConfig_straff_Smp_112405_Dt_05_08_12_00.txt").

**Comment by jturner65** [comment]
why are these breaking now?  none of this has changed since August.  It's irrelevant, really, the code uses File.separator everywhere the code is generated- whenever a map is trained from scratch, it will write the file information using the OS specific markers.

**Comment by jturner65** [comment]
Until i get around addressing this, i would suggest re-running the code to generate a map on the resident OS and then using that as a default map - this is only an issue with the prebuilt map configuration file, which i synthesized on my machine, and not anything in the code.
